"""Live emulator memory bridge readers.

This module intentionally avoids direct process memory scanning and instead
consumes a local bridge payload generated by emulator scripting.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict
import json
import re
import time

from party_parser import SPECIES_MAP, SPECIES_TYPES_MAP


class MemoryReaderUnavailableError(RuntimeError):
    pass


@dataclass
class MemoryReaderConfig:
    bridge_path: Path
    stale_after_seconds: float = 2.0


class BaseMemoryReader:
    def read_state(self) -> Dict[str, Any]:
        raise NotImplementedError


class MgbaJsonBridgeReader(BaseMemoryReader):
    """Reads a live state JSON payload produced by an mGBA script bridge.

    Expected payload shape:
    {
      "party": [...],
      "pc": [...],
      "dead": [...],
      "meta": {...},
      "timestamp_ms": 1716000000000
    }
    """

    def __init__(self, config: MemoryReaderConfig):
        self._config = config

    def _normalize_mon(self, mon: Any) -> Any:
        if not isinstance(mon, dict):
            return mon

        species_id = mon.get("species_id")
        species = mon.get("species")

        if not isinstance(species_id, int) and isinstance(species, str):
            match = re.fullmatch(r"species_(\d+)", species.strip().lower())
            if match:
                try:
                    species_id = int(match.group(1))
                except ValueError:
                    species_id = None

        if isinstance(species_id, int):
            canonical = SPECIES_MAP.get(species_id)
            if canonical:
                mon["species"] = canonical
            elif not isinstance(species, str) or not species.strip():
                mon["species"] = f"species_{species_id}"

            if not mon.get("types"):
                mapped_types = SPECIES_TYPES_MAP.get(species_id)
                if mapped_types:
                    mon["types"] = mapped_types

        return mon

    def _normalize_party_like(self, mons: Any) -> Any:
        if not isinstance(mons, list):
            return mons
        return [self._normalize_mon(mon) for mon in mons]

    def _is_suspicious_pc_mon(self, mon: Any) -> bool:
        if not isinstance(mon, dict):
            return True

        species_id = mon.get("species_id")
        box = mon.get("box")
        box_slot = mon.get("box_slot")
        if not isinstance(species_id, int) or species_id <= 0 or species_id > 3000:
            return True
        if not isinstance(box, int) or box <= 0:
            return True
        if not isinstance(box_slot, int) or box_slot <= 0:
            return True

        held_item = mon.get("held_item")
        if isinstance(held_item, str) and held_item.strip().lower() == "item_65535":
            return True

        nickname = mon.get("nickname")
        if not isinstance(nickname, str) or not nickname.strip():
            return True

        return False

    def _read_bridge_payload_with_retry(self) -> Dict[str, Any]:
        last_exc: Exception | None = None
        # The bridge writer can briefly expose partially-written JSON on some
        # Windows setups. Retry for a wider window before marking unavailable.
        for _attempt in range(20):
            try:
                text = self._config.bridge_path.read_text(encoding="utf-8")
                if not text or not text.strip():
                    raise MemoryReaderUnavailableError("Memory bridge JSON is empty")
                payload = json.loads(text)
                if not isinstance(payload, dict):
                    raise MemoryReaderUnavailableError("Memory bridge JSON root is not an object")
                return payload
            except FileNotFoundError as exc:
                last_exc = exc
            except PermissionError as exc:
                last_exc = exc
            except json.JSONDecodeError as exc:
                last_exc = exc
            except MemoryReaderUnavailableError as exc:
                last_exc = exc

            # Bridge writer replaces files atomically; short waits avoid transient races.
            time.sleep(0.03)

        if isinstance(last_exc, FileNotFoundError):
            raise MemoryReaderUnavailableError(
                f"Memory bridge file not found: {self._config.bridge_path}"
            )
        if isinstance(last_exc, PermissionError):
            raise MemoryReaderUnavailableError(
                f"Memory bridge file temporarily locked: {self._config.bridge_path}"
            )
        if isinstance(last_exc, json.JSONDecodeError):
            raise MemoryReaderUnavailableError(
                f"Invalid memory bridge JSON: {last_exc}"
            )
        if isinstance(last_exc, MemoryReaderUnavailableError):
            raise last_exc

        raise MemoryReaderUnavailableError(
            f"Unable to read memory bridge payload: {self._config.bridge_path}"
        )

    def read_state(self) -> Dict[str, Any]:
        try:
            stat = self._config.bridge_path.stat()
        except FileNotFoundError as exc:
            raise MemoryReaderUnavailableError(
                f"Memory bridge file not found: {self._config.bridge_path}"
            ) from exc
        except PermissionError as exc:
            raise MemoryReaderUnavailableError(
                f"Memory bridge file temporarily locked: {self._config.bridge_path}"
            ) from exc

        age_seconds = max(0.0, time.time() - stat.st_mtime)
        if age_seconds > self._config.stale_after_seconds:
            raise MemoryReaderUnavailableError(
                "Memory bridge payload is stale "
                f"({age_seconds:.2f}s old, threshold={self._config.stale_after_seconds:.2f}s)"
            )

        payload = self._read_bridge_payload_with_retry()

        party = payload.get("party", [])
        pc = payload.get("pc", [])
        dead = payload.get("dead", [])
        meta = payload.get("meta", {})

        if not isinstance(party, list):
            raise MemoryReaderUnavailableError("Memory bridge 'party' is not an array")
        if not isinstance(pc, list):
            pc = []
        if not isinstance(dead, list):
            dead = []
        if not isinstance(meta, dict):
            meta = {}

        timestamp_ms = payload.get("timestamp_ms")
        if isinstance(timestamp_ms, (int, float)):
            ts_value = float(timestamp_ms)
            # Some Lua bridges use os.clock(), which is process uptime and not epoch.
            # In that case, rely on file mtime freshness checks above.
            if ts_value >= 1_000_000_000_000:
                age_from_payload = max(0.0, (time.time() * 1000 - ts_value) / 1000.0)
                if age_from_payload > self._config.stale_after_seconds:
                    raise MemoryReaderUnavailableError(
                        "Memory bridge timestamp is stale "
                        f"({age_from_payload:.2f}s old, threshold={self._config.stale_after_seconds:.2f}s)"
                    )

        out = {
            "party": self._normalize_party_like(party),
            "pc": self._normalize_party_like(pc),
            "dead": self._normalize_party_like(dead),
            "meta": meta,
        }

        out["pc"] = [mon for mon in out["pc"] if not self._is_suspicious_pc_mon(mon)]

        return out


def build_memory_reader(
    *,
    backend: str,
    bridge_path: Path,
    stale_after_seconds: float,
) -> BaseMemoryReader:
    normalized = str(backend or "mgba_json_bridge").strip().lower()
    config = MemoryReaderConfig(
        bridge_path=bridge_path,
        stale_after_seconds=max(0.2, float(stale_after_seconds)),
    )

    if normalized == "mgba_json_bridge":
        return MgbaJsonBridgeReader(config)

    raise MemoryReaderUnavailableError(f"Unsupported memory backend: {backend}")
